FROM alpine:3.7
WORKDIR /app
RUN apk --no-cache add python3 python3-dev gcc git musl-dev libffi-dev openssl-dev \
        && pip3 install steem \
        && pip3 install pymysql \
        && pip3 install aiomysql \
        && pip3 install diff_match_patch
ENV WORKER=1 \
           BLOCK_STEP=1000 \
           SLICE_STEP=5 \
           UNDO_LIMIT=50 \
           UNDO_COUNT=50 \
           UNDO_SLEEP=5 \
           BASE_SLEEP=3 \
           STEEMDB_CONFIG='{"host": "steem-lightdb.com", "port": 3306, "user": "steem", "pass": "steem", "db": "steemdb"}' \
           STEEM_CONFIG='{"host": "172.20.0.4", "port": 3306, "user": "root", "pass": "123456", "db": "steem"}'
COPY . /app
CMD ["/bin/ash"]
